env: dev
baseDomain: coreos-dev.fxtrt.io
namespace: tenant-developerplatform
service_name: console-api
gateway_name: fxtrt-apps
apps:
  consoleapi:
    replicaCount: 1
    image:
      repository: 217425097687.dkr.ecr.ap-south-1.amazonaws.com/developer-platform/console-api
      version: 0.0.1-dev-a200421
    resourceType: m1
    api:
      path: /app/console-api
      health: /app/console-api/health
    unAuthPaths: /app/console-api/*
    unAuthMethods: OPTIONS
    port: 3000
    corsHeaders:
      - X-DEVELOPERPLATFORM-ACCESS
      - X-DEVELOPERPLATFORM-USER-ID
      - X-DEVELOPERPLATFORM-ROLE
      - X-DEVELOPERPLATFORM-REQUEST-ID
      - X-COREOS-TID
      - X-COREOS-ACCESS
      - X-COREOS-REQUEST-ID
      - Content-Type
    envVars:
      - name: APPLICATION_SERVICE_ENDPOINT
        value: application-service-applicationservice.tenant-developerplatform.svc.cluster.local:50052
      - name: SOLUTION_SERVICE_ENDPOINT
        value: solutions-service-solutionsservice.tenant-developerplatform.svc.cluster.local:50052
      - name: SUBSCRIPTION_SERVICE_ENDPOINT
        value: subscription-service-subscriptionservice.tenant-developerplatform.svc.cluster.local:50052
      - name: COREOS_AGENT_SERVICE_ENDPOINT
        value: coreos-agent-coreosagent.tenant-developerplatform.svc.cluster.local:50052
      - name: FILE_SERVICE_ENDPOINT
        value: file-service-fileservice.tenant-developerplatform.svc.cluster.local:50052
    externalAccess:
      enabled: true
    autoscaling:
      enabled: false
    authentication:
      enabled: true
      authorizationProvider: developer-platform
    podAnnotations: {}
