env: prod
namespace: tenant-developerplatform
service_name: console-api
gateway_name: fxtrt-apps
apps:
  consoleapi:
    replicaCount: 3
    image:
      repository: 429738059147.dkr.ecr.ap-south-1.amazonaws.com/developer-platform/console-api
      version: 0.0.1-prod-4d843b7
    resourceType: m1
    api:
      path: /app/console-api
      health: /app/console-api/health
    unAuthPaths: /app/console-api/*
    unAuthMethods: OPTIONS
    port: 3000
    corsHeaders:
      - X-DEVELOPERPLATFORM-ACCESS
      - X-DEVELOPERPLATFORM-USER-ID
      - X-DEVELOPERPLATFORM-ROLE
      - X-DEVELOPERPLATFORM-REQUEST-ID
      - X-COREOS-TID
      - X-COREOS-ACCESS
      - X-COREOS-REQUEST-ID
      - Content-Type
    externalAccess:
      enabled: true
    autoscaling:
      enabled: false
    authentication:
      enabled: true
      authorizationProvider: developer-platform
    podAnnotations: {}
