name: Validate pull request

on:
  pull_request:
    branches:
      - development
  workflow_dispatch:

jobs:
  pr-standard:
    name: PR Standards
    uses: FoxtrotPlatform/developer-platform-github-workflow/.github/workflows/dev-pr-standards.yaml@main
    secrets:
      f_github_token: ${{ secrets.F_GITHUB_TOKEN }}
      ado_user_name: ${{ secrets.ADO_USERNAME }}
      ado_pat: ${{ secrets.ADO_PAT }}
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19"
      - name: Install Yarn
        shell: "bash"
        run: npm install -g yarn
      - name: Install Dependencies
        run: |
          git config --global url."https://${{ secrets.CICD_KEY}}@github.com/".insteadOf ssh://git@github.com/
          echo -e "@foxtrotplatform:registry=https://npm.pkg.github.com\n//npm.pkg.github.com/:_authToken=${{ secrets.F_GITHUB_TOKEN }}" > .npmrc
          yarn install
      - name: Generate schemas
        run: |
          mkdir -p src/shared/schemas
          yarn _proto:gen
      - name: Build
        run: yarn build
      - name: Test
        run: |
          yarn test:cov --ci --testLocationInResults --reporters=default --reporters=github-actions --coverageReporters=cobertura --coverageDirectory=coverage
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.2.0
        with:
          filename: coverage/cobertura-coverage.xml
          format: markdown
          output: both
          indicators: true
          badge: true
      - name: Add title to file
        run: cat code-coverage-results.md > /tmp/out && mv /tmp/out code-coverage-results.md
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          comment: coverage summary
          header: coverage summary
          path: code-coverage-results.md
